	public static final  A
	public static final  B
	public static final  C
	public static final  D
	public static final  E
	public static final  F
	public static final  G
	public static final  H
	public static final  I
	public static final  J
	public static final  K
	public static final  L
	public static final  M
	public static final  N
	public static final  O
	public static final  P
	public static final  Q
	public static final  R
	public static final  S
	public static final  T
	public static final  U
	public static final  V
	public static final  W
	public static final  X
	public static final  Y
	public static final  Z
	public static final  aA
	public static final  aB
	public static final  aC
	public static final  aD
	public static final  aE
	public static final  aF
	public static final  aG
	public static final  aH
	public static final  aI
	public static final  aJ
	public static final  aK
	public static final  aL
	public static final  aM
	public static final  aN
	public static final  aO
	public static final  aP
	public static final  aQ
	public static final  aR
	public static final  aS
	public static final  aT
	public static final  aU
	public static final  aV
	public static final  aW
	public static final  aX
	public static final  aY
	public static final  aZ
	public static final  aa
	public static final  ab
	public static final  ac
	public static final  ad
	public static final  ae
	public static final  af
	public static final  ag
	public static final  ah
	public static final  ai
	public static final  aj
	public static final  ak
	public static final  al
	public static final  am
	public static final  an
	public static final  ao
	public static final  ap
	public static final  aq
	public static final  ar
	public static final  as
	public static final  at
	public static final  au
	public static final  av
	public static final  aw
	public static final  ax
	public static final  ay
	public static final  az
	public static final  bA
	public static final  bB
	public static final  bC
	public static final  bD
	public static final  bE
	public static final  bF
	public static final  bG
	public static final  bH
	public static final  bI
	public static final  bJ
	public static final  bK
	public static final  bL
	public static final  bM
	public static final  bN
	public static final  bO
	public static final  bP
	public static final  bQ
	public static final  bR
	public static final  bS
	public static final  bT
	public static final  bU
	public static final  bV
	public static final  bW
	public static final  bX
	public static final  bY
	public static final  bZ
	public static final  ba
	public static final  bb
	public static final  bc
	public static final  bd
	public static final  be
	public static final  bf
	public static final  bg
	public static final  bh
	public static final  bi
	public static final  bj
	public static final  bk
	public static final  bl
	public static final  bm
	public static final  bn
	public static final  bo
	public static final  bp
	public static final  bq
	public static final  br
	public static final  bs
	public static final  bt
	public static final  bu
	public static final  bv
	public static final  bw
	public static final  bx
	public static final  by
	public static final  bz
	public static final  cA
	public static final  cB
	public static final  cC
	public static final  cD
	public static final  cE
	public static final  cF
	public static final  cG
	public static final  cH
	public static final  cI
	public static final  cJ
	public static final  cK
	public static final  cL
	public static final  cM
	public static final  cN
	public static final  cO
	public static final  cP
	public static final  cQ
	public static final  cR
	public static final  cS
	public static final  cT
	public static final  cU
	public static final  cV
	public static final  cW
	public static final  cX
	public static final  cY
	public static final  cZ
	public static final  ca
	public static final  cb
	public static final  cc
	public static final  cd
	public static final  ce
	public static final  cf
	public static final  cg
	public static final  ch
	public static final  ci
	public static final  cj
	public static final  ck
	public static final  cl
	public static final  cm
	public static final  cn
	public static final  co
	public static final  cp
	public static final  cq
	public static final  cr
	public static final  cs
	public static final  ct
	public static final  cu
	public static final  cv
	public static final  cw
	public static final  cx
	public static final  cy
	public static final  cz
	public static final  dA
	public static final  dB
	public static final  dC
	public static final  dD
	public static final  dE
	public static final  dF
	public static final  dG
	public static final  dH
	public static final  dI
	public static final  dJ
	public static final  dK
	public static final  dL
	public static final  dM
	public static final  dN
	public static final  dO
	public static final  dP
	public static final  dQ
	public static final  dR
	public static final  dS
	public static final  dT
	public static final  dU
	public static final  dV
	public static final  dW
	public static final  dX
	public static final  dY
	public static final  dZ
	public static final  da
	public static final  db
	public static final  dc
	public static final  dd
	public static final  de
	public static final  df
	public static final  dg
	public static final  dh
	public static final  di
	public static final  dj
	public static final  dk
	public static final  dl
	public static final  dm
	public static final  dn
	public static final  do
	public static final  dp
	public static final  dq
	public static final  dr
	public static final  ds
	public static final  dt
	public static final  du
	public static final  dv
	public static final  dw
	public static final  dx
	public static final  dy
	public static final  dz
	public static final  e
	public static final  eA
	public static final  eB
	public static final  eC
	public static final  eD
	public static final  eE
	public static final  eF
	public static final  eG
	public static final  eH
	public static final  eI
	public static final  ea
	public static final  eb
	public static final  ec
	public static final  ed
	public static final  ee
	public static final  ef
	public static final  eg
	public static final  eh
	public static final  ei
	public static final  ej
	public static final  ek
	public static final  el
	public static final  em
	public static final  en
	public static final  eo
	public static final  ep
	public static final  eq
	public static final  er
	public static final  es
	public static final  et
	public static final  eu
	public static final  ev
	public static final  ew
	public static final  ex
	public static final  ey
	public static final  ez
	public static final  f
	public static final  g
	public static final  h
	public static final  i
	public static final  j
	public static final  k
	public static final  l
	public static final  m
	public static final  n
	public static final  o
	public static final  p
	public static final  q
	public static final  r
	public static final  s
	public static final  t
	public static final  u
	public static final  v
	public static final  w
	public static final  x
	public static final  y
	public static final  z
	public ed a
	public java.util.ArrayList b
	public ak c
	public android.view.View d
	
	    private f()
	    {
	        return;
	    }
	
	
	    public f(c p2)
	    {
	        this.a = new ed();
	        this.b = new java.util.ArrayList();
	        this.c = new ak();
	        return;
	    }
	
